categories:
  - title: "Breaking Changes"
    label: "breaking"
  - title: "Features"
    label: "enhancement"
  - title: "Removals and Deprecations"
    label: "removal"
  - title: "Fixes"
    label: "bug"
  - title: "Performance"
    label: "performance"
  - title: "Testing"
    label: "testing"
  - title: "Continuous Integration"
    label: "ci"
  - title: "Documentation"
    label: "documentation"
  - title: "Refactoring"
    label: "refactoring"
  - title: "Style"
    label: "style"
  - title: "Dependencies"
    labels:
      - "dependencies"
      - "build"
template: |
  ## Changes

  $CHANGES
