name: Run HassFest

on:
  pull_request:
    paths:
      - "homeassistant/**"
      - ".github/workflows/hassfest.yml"

jobs:
  hassfest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run HassFest
        uses: home-assistant/actions/hassfest@main
